# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


target 'Test-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-desktop

end

target 'Test-mobile' do
 
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-mobile

end
